version: "3"

services:
  obg-server:
    build: .
    expose:
      - 3000
    labels:
      - traefik.http.routers.obg-server.rule=Host(`localhost`) # todo

  traefik:
    image: traefik:v2.3
    ports:
      - 8080:80
      - 8443:443
      - 8001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml
